### ISSUE TITLE
CAS CDN error for 21742 after recent merge

### ISSUE THREAD

**Issue by tomalaci** [trinity6/trinity6.github.io#15]
![d232b868dc9f4dbfb57a6d37e8fa2b5a](https://cloud.githubusercontent.com/assets/8745995/17629017/e703b31c-60c0-11e6-8644-df4a32ac93df.png)

The above error is appearing for my enUS 21742 WoD installation quite recently and within the timeframe of this merge: bdca741006bacb5afccf9f0097750b1ad990d6a3

How would I fix this if the cause comes from this merge? Should I export old version of 21472 CDN file to a private website and patch the client to use that or...?

**Comment by funjoker** [comment]
You have older 21742 Version.
Reinstall your WoW and it works

**Comment by funjoker** [comment]
can you send me your version of Wow.exe ?

**Comment by funjoker** [comment]
i try to find solution

**Comment by funjoker** [comment]
I used a 21742 versioned WoW.exe and it works for me.
Try to reinstall WoW with the patched exe.

**Comment by tomalaci** [comment]
https://drive.google.com/open?id=0B9bR-Dw6svB7UnpoSzBxQWhaSDQ

^ the patched .exe file

Also, it seems that some other users do not have this problem, while many others do and apparently they haven't changed anything. They all also use the same WoW files.

**Comment by tomalaci** [comment]
Here is link to WoW/Data/config folder in archive format in case if its of any use:
https://drive.google.com/open?id=0B9bR-Dw6svB7dE9ESHVCY2dobVk

**Comment by tomalaci** [comment]
After further investigation, it appears that me and many other users (who also had this problem) were missing WoW/Data/config/ee/e4/eee453d9035886d03a1308de041de88c file (hence, you were right about having older 21742 version, but fortunately one does not need to reinstall whole thing). Distributing it to others and  applying it for myself fixed the issue. I'll wait for you to reply before closing the issue.

**Comment by funjoker** [comment]
Repatching the wow.exe might also fix that Problem.
