### ISSUE TITLE
versi 20779

### ISSUE THREAD

**Issue by devovh** [trinity6/trinity6.github.io#50]
Please add 20779, wow no start error cas

**Comment by Aokromes** [comment]
Update to 6.2.4.21742

**Comment by devovh** [comment]
And there is a way for me to work on this version depends on me. "20779"

**Comment by funjoker** [comment]
i'll check that

**Comment by funjoker** [comment]
3a4c479cc053f9aac0730dbe2b8d7f199cf3f921

**Comment by funjoker** [comment]
If you have the old 6.2.3 client, can you please provide me all data inside Data/config?
